# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NHLThread' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NHLThread
  pod 'ReactiveCocoa', '2.5'
  pod 'Masonry', '1.1.0'

  target 'NHLThreadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NHLThreadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
